# Generated by Django 4.0.4 on 2022-05-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=250, verbose_name='full name')),
                ('student_id', models.CharField(max_length=150, unique=True, verbose_name='student id')),
                ('batch_no', models.IntegerField(unique=True, verbose_name='batch no')),
                ('linkend_id', models.URLField(blank=True, null=True, verbose_name='linkend id')),
                ('club_admin', models.CharField(blank=True, max_length=50, null=True, verbose_name='club admin')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_member', models.BooleanField(default=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
