# Generated by Django 4.0.4 on 2022-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='full name'),
        ),
    ]
