# Generated by Django 4.0.4 on 2022-05-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auser', '0002_alter_associationuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationuser',
            name='batch_no',
            field=models.CharField(max_length=40, unique=True, verbose_name='batch no'),
        ),
    ]
