# Generated by Django 4.0.4 on 2022-05-27 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, unique=True)),
                ('club_image', models.ImageField(upload_to='club')),
                ('club_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs')),
            ],
        ),
        migrations.CreateModel(
            name='WebNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=39)),
                ('batch_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=11)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubin', verbose_name='club name')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=39)),
                ('batch_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=11)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubin', verbose_name='club name')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=39)),
                ('batch_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=11)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubin', verbose_name='club name')),
            ],
        ),
        migrations.CreateModel(
            name='HardWareHacking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=39)),
                ('batch_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=11)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubin', verbose_name='club name')),
            ],
        ),
        migrations.CreateModel(
            name='Cultaral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=39)),
                ('batch_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=11)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubin', verbose_name='club name')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.associationclub')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=39)),
                ('batch_number', models.IntegerField()),
                ('student_name', models.CharField(max_length=150)),
                ('student_nickname', models.CharField(blank=True, max_length=150, null=True)),
                ('student_email', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=11)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubin', verbose_name='club name')),
            ],
        ),
    ]
