# Generated by Django 4.0.4 on 2022-05-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmember',
            old_name='club_name',
            new_name='club',
        ),
    ]
